VEHICLE_ID:
BATTERY_LEVEL: 80 # value in %
CHARGING_PORT: 'AC' # DC: CHAdeMO >= 50kW | AC >= 6.6kW (europe)
MAX_BATTERY_CAPACITY_IN_KWH: 30 # max battery capacity in KWH
ACTUAL_BATTERY_STATUS_IN_KWH: 0 # actual bettery capacity in KWH
BATTERY_VOLTAGE: 356
COOLING_SYSTEM: "PASSIVE" # LIQUID = HIGH EFECTIVE | AIR = MEDIUM EFECTIVE | PASSIVE = LOW EFFECTIVE
LOG_LEVEL_VEHICLE: "debug"