# CONFIG FOR PRE COMMIT FORMATTER (manual run: pre-commit run --all-files  )
[tool.black]
line-length = 100
skip-string-normalization = true

[tool.isort]
line_length = 100
profile = 'black'

[tool.flake8]
max-line-length = 200

#CONFIG PYTEST FOR AUTOMATION TESTS
[tool.pytest.ini_options]
pythonpath = [
  "CHARGER", "VEHICLE"
]
[tool.unittest.ini_options]
pythonpath = [
  "CHARGER", "VEHICLE"
]
