# Charger server config
SERVER_APP: "Charger:app"
HOST_IP: "127.0.0.1"
PORT: 5000
RELOAD: False
LOG_DIR: "logs" # directory to save logs
LOG_LEVEL: 20 # log levels in int || 10 = debug | 20 = info | 30 = warning | 40 = error | 50 = critical
LOG_LEVEL_CONSOLE: 20 # log levels in int || 10 = debug | 20 = info | 30 = warning | 40 = error | 50 = critical
LOG_LEVEL_SERVER: 20 # log levels in int || 10 = debug | 20 = info | 30 = warning | 40 = error | 50 = critical
